<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjutkan Pembelian</name>
   <tag></tag>
   <elementGuidId>279460cc-8ef8-49ca-936d-49b9d1ed01ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#go_to_next_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go_to_next_page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a67c3fcf-0b4e-4089-8e55-7a100c1818e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>627a8dbf-c2f1-4891-bf32-d49da60f5072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-rose</value>
      <webElementGuid>96b000bc-7fae-4a24-89a6-e9d4f9090981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go_to_next_page</value>
      <webElementGuid>ec3e623f-6ded-45ad-ab54-6a4a82738f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan Pembelian</value>
      <webElementGuid>2e15c8f2-0fe6-41a3-bbcc-70712517f527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go_to_next_page&quot;)</value>
      <webElementGuid>4d27218f-c8dd-4f3a-b209-9ff8ca232513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go_to_next_page']</value>
      <webElementGuid>30cbf446-1cfd-4c94-a06d-6d59cdfcbe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_next_page_order']/button</value>
      <webElementGuid>366ef1a0-c922-4905-b34a-6b5b8f1fb321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::button[1]</value>
      <webElementGuid>db055938-15e4-4657-b92e-5fa11aaacea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::button[2]</value>
      <webElementGuid>61feb087-ecd9-4fef-9df1-787bfd034ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update layanan'])[1]/preceding::button[1]</value>
      <webElementGuid>9201e858-bec4-4150-b93d-33dab33fdf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/preceding::button[2]</value>
      <webElementGuid>b1afe322-a021-4b09-8985-c31adfdebda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan Pembelian']/parent::*</value>
      <webElementGuid>4a21d2de-933f-4c01-9a52-7c519e73f431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/button</value>
      <webElementGuid>e04e596e-58e0-460c-a351-7e2758d2bf8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'go_to_next_page' and (text() = 'Lanjutkan Pembelian' or . = 'Lanjutkan Pembelian')]</value>
      <webElementGuid>dd9e8664-3650-4028-93f4-f0d03600cf0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
