<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pesan</name>
   <tag></tag>
   <elementGuidId>ce7289c1-70c0-454b-8d1d-d1627e489a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pesan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pesan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e3d52b0-53a0-4e89-85a7-b72d5f945bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>12e96312-5878-46f1-8a9b-1587d7c5164f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-fill btn-rose</value>
      <webElementGuid>499555e1-b282-4b5b-9844-9dc7facbb27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pesan</value>
      <webElementGuid>bede1fe2-2ede-41c2-af89-9274c07a4aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pesan</value>
      <webElementGuid>681e80a3-c353-40e0-9b52-57926d2af258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan</value>
      <webElementGuid>b55c1e7c-730e-482d-bb20-98d168ae7b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pesan&quot;)</value>
      <webElementGuid>2928e5e2-9184-4428-8849-eb8b2d996fbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pesan']</value>
      <webElementGuid>f65f6720-adc6-4367-901d-1af64e73553e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_order']/div/div[2]/div[12]/button</value>
      <webElementGuid>5bd2e523-4189-4c5c-86c3-6a9c8d345424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 500'])[1]/following::button[1]</value>
      <webElementGuid>727b8aaf-61e0-4d81-9855-bb2912d45702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='perm_identity'])[1]/preceding::button[1]</value>
      <webElementGuid>dc4d2483-71fc-4220-907f-dbc287be1b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Penting'])[1]/preceding::button[1]</value>
      <webElementGuid>a31ca36e-2716-4aab-a108-135be4523d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan']/parent::*</value>
      <webElementGuid>5c083213-0f45-49a4-a189-9b0998541fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/button</value>
      <webElementGuid>2d3ca32f-7b72-45cc-9f17-5bbadf7e7d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'pesan' and @name = 'pesan' and (text() = 'Pesan' or . = 'Pesan')]</value>
      <webElementGuid>cf1e31af-eac6-4102-a963-65d9b005dcb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
