<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Post_value</name>
   <tag></tag>
   <elementGuidId>f2cb89d8-f2ed-4535-9c6a-45936c7a1d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#posts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='posts']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b11dcfce-3cfc-447a-9c0f-a8bf82a0297d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dee0cad6-9d57-4457-9c24-fb85ed92774a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e2fbded3-9357-4416-88ba-1979ef262edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>1988e891-d4ee-4d2e-b1e6-bee8c10c7697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value[]</value>
      <webElementGuid>0e2a9423-241a-4363-9bb3-106063c1d4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>posts</value>
      <webElementGuid>a42487f5-46cc-455e-b0b5-96152feb3daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah post maks 250</value>
      <webElementGuid>daf116d2-c9db-40e7-b84e-a6d4d5c22c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a98ce105-9c53-4bb9-bbf1-64bb385c55ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>set_total_subs(this)</value>
      <webElementGuid>ba014e70-115f-405a-9d28-bcc23e84bc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_input&quot;)/div[2]/div[@class=&quot;form-group has-default&quot;]/div[@class=&quot;form-group bmd-form-group&quot;]/input[@id=&quot;posts&quot;]</value>
      <webElementGuid>47d30dbb-e068-407f-a8fa-6f770cef685b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='posts']</value>
      <webElementGuid>08562d66-38d6-4f93-9257-99d37dccdb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_input']/div[2]/div/div/input</value>
      <webElementGuid>9332eb9d-250e-44bc-8f15-0889b82c3809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>3e1e704a-0d79-42a0-b7b6-7b1bf59fdfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'value[]' and @id = 'posts' and @placeholder = 'Jumlah post maks 250']</value>
      <webElementGuid>77974a88-8ab9-440b-a1e1-065cb9c7f8c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
