<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Like  View Per Post_value</name>
   <tag></tag>
   <elementGuidId>6b433eed-0e85-46c3-8657-7c3963d95807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#min</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='min']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>516f21ef-8546-46ee-bd51-cf356d4f02d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0fedacdd-278c-45fc-b480-95b79a9898bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value[]</value>
      <webElementGuid>0a172cb7-78f5-497f-a187-d6dd8901a4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>min</value>
      <webElementGuid>d18dbcd2-6d90-4eaa-becd-7108e1084afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah like / view per post</value>
      <webElementGuid>9c4175f3-1d80-4c6b-9cce-8c3f88879597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6b349ef-a75d-43ae-8d6d-19f70dbda998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>set_total_subs(this)</value>
      <webElementGuid>5c8f4427-f54c-42ed-be33-3fd35ee955a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>252b1fa5-5df1-434f-a26a-0acfbe1a425b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>20f4a03b-bb2a-494e-92eb-58c553adfd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_input&quot;)/div[1]/div[@class=&quot;form-group has-default&quot;]/div[@class=&quot;form-group bmd-form-group&quot;]/input[@id=&quot;min&quot;]</value>
      <webElementGuid>06a62d98-6581-48f0-800b-ca391579e32e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='min']</value>
      <webElementGuid>8b32cd37-9692-4ee4-8b9c-5c762ac671da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_input']/div/div/div/input</value>
      <webElementGuid>81afbf19-5a5d-4de1-ad02-5248c1d7181a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>fd567b8f-09b1-4d0f-b39a-ddaf195d560c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'value[]' and @id = 'min' and @placeholder = 'Jumlah like / view per post']</value>
      <webElementGuid>4d406b7e-293f-411d-8d9f-d6f337b63432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
