<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ambil foto dari instagram_target</name>
   <tag></tag>
   <elementGuidId>e88979c1-2e69-400f-842b-690b3e89ad13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='target']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fb4ff40-051b-4712-8c1c-a184f525d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f620a79-9efe-40e9-b457-9f9fe7ecb765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>target</value>
      <webElementGuid>dd1ebae2-de1e-4da5-87ae-d5e4575e5c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target</value>
      <webElementGuid>25f5c430-08c9-4840-b675-5570a074fe10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>66ee2082-f89c-49ba-a8fd-761a59eaeef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target&quot;)</value>
      <webElementGuid>baf19ed5-c728-4c1a-88cf-4c715e4f2776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='target']</value>
      <webElementGuid>851975d3-a81c-476a-bd3e-bb6ec424d1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_order']/div/div[2]/div[6]/div[2]/div/input</value>
      <webElementGuid>0635a6cd-8bb5-4e6a-9449-6597870345a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/input</value>
      <webElementGuid>842deb38-2dc1-48ff-baeb-8849951759ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'target' and @id = 'target']</value>
      <webElementGuid>4890b557-5180-484f-9b44-f856effa7f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
