<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Layanan_new_id_product</name>
   <tag></tag>
   <elementGuidId>7f72884c-5d6c-4d92-92a8-fd19e2723059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new_id_product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new_id_product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cc4db25-cbc3-4406-9079-f7e950819895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da79576c-b2bc-40a2-868b-93da136614ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>af6b0645-ca4c-4eac-8f0e-2b336dcea160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_id_product</value>
      <webElementGuid>ac893f15-4838-4b40-aded-176c071a423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih kategori terlebih dahulu</value>
      <webElementGuid>26e26aab-0a0f-4e0c-9eeb-ff10e35f9b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_id_product&quot;)</value>
      <webElementGuid>b8e16340-f961-4c22-b0e2-2d81b75b3531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new_id_product']</value>
      <webElementGuid>ac9b0802-4c83-457e-b596-c1b99ce68628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pilih_kategory']/div/input</value>
      <webElementGuid>22aba4f6-28ee-4404-98e0-d21653e0230a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>be294111-92f4-401a-97cc-d4fdf34543c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'new_id_product' and @placeholder = 'Pilih kategori terlebih dahulu']</value>
      <webElementGuid>9dd9ce9d-4a1f-4962-86d5-eebf84ba0b75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
