<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Pesanan_qty</name>
   <tag></tag>
   <elementGuidId>324735ca-6a0f-46c8-b711-0c20df3cc93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51cb1a95-adcc-4ea3-a2cc-4022a4faa3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7033c760-0cad-4040-9ac0-2071f989732e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80513772-1017-4999-9cba-e5f3663f809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validity.valid||(value='');</value>
      <webElementGuid>b56528fe-052d-4d7e-a181-bd4b911f9560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>713c4c11-43e7-4ce6-872a-13d552a4b6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ajax_set_max()</value>
      <webElementGuid>efec0ccf-0714-4040-807f-eb3d576d1d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>617e5662-2b91-46fd-9fe8-f1740868ac2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d10bdbd-3a8f-4313-880c-d501e9565bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>bd8bc7ce-63ae-4f2b-ac37-6f923c822dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c4ea655b-a1f0-40d5-ba5a-f6bee8d7bbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty&quot;)</value>
      <webElementGuid>abd1b40e-c614-4122-a2a6-e651c1b18243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qty']</value>
      <webElementGuid>e48babb1-6b5e-49c4-a614-a6c71190e436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qty_all']/div/div/input</value>
      <webElementGuid>5058e2da-6318-4444-b4c6-766849131f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>4d1935ce-9c66-4b26-8af8-13e6cba1f384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'qty' and @id = 'qty']</value>
      <webElementGuid>b8eadffa-cdfd-4e1f-8854-b46777a48944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
