<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Waktu Jeda0510306090</name>
   <tag></tag>
   <elementGuidId>9ed5d427-5584-407f-b6fc-e47ffbee8785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='delay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed037683-a660-463d-91c8-88ac8051dc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delay</value>
      <webElementGuid>af0b7590-4a68-4ccb-b7d9-a9e98df020c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value[]</value>
      <webElementGuid>da3f06d3-cc4d-433e-bfb3-6c74307730f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8470fc79-ff64-4dc2-bab6-cfb96968fe02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Waktu Jeda0510306090</value>
      <webElementGuid>d4dfdb60-91d4-4297-9ed4-59b6f2f0bd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_input&quot;)/div[3]/div[@class=&quot;form-group has-default&quot;]/div[@class=&quot;form-group&quot;]/select[@id=&quot;delay&quot;]</value>
      <webElementGuid>6bf49a2b-bb6a-47fb-b555-2bafda1787fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='delay']</value>
      <webElementGuid>8a430052-f69d-447b-9edc-bd7cc2d71dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_input']/div[3]/div/div/select</value>
      <webElementGuid>fc8d9b91-744a-4de6-9dd1-2be158665cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeda (menit)'])[1]/following::select[1]</value>
      <webElementGuid>4f515595-126d-479f-b91f-6f1ae9ddecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Post'])[1]/following::select[1]</value>
      <webElementGuid>19331d8c-82a7-4a7a-84dc-ae91b452b949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Pesanan'])[1]/preceding::select[1]</value>
      <webElementGuid>c5fdec0b-5610-4977-9f76-69e8f54b0194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>7535cee2-bcda-40ff-bc04-963c6fbe982f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'delay' and @name = 'value[]' and (text() = 'Pilih Waktu Jeda0510306090' or . = 'Pilih Waktu Jeda0510306090')]</value>
      <webElementGuid>7338e019-93e6-430f-8142-5806178a9d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
