<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_List Komentar_value</name>
   <tag></tag>
   <elementGuidId>79ae3de9-caa3-4c37-a853-62c96afda9c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e39fc1e1-eb82-42c2-9547-34da68625e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>76a83ee1-9661-4e99-a5f7-f77f2701a970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value[]</value>
      <webElementGuid>1101286b-f5ac-46c9-b0e7-6aff3e3089b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control count</value>
      <webElementGuid>c3c2f755-96c8-4364-bd15-e17cd1f06238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>comment()</value>
      <webElementGuid>8b0f1d62-207b-4f88-afb7-a48d8df33393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_input&quot;)/div[1]/div[@class=&quot;form-group has-default&quot;]/div[@class=&quot;form-group bmd-form-group is-focused is-filled&quot;]/textarea[@id=&quot;comments&quot;]</value>
      <webElementGuid>6a55aab6-37eb-4277-9374-a7e822330ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comments']</value>
      <webElementGuid>5da09411-aff5-4ea8-93c0-6534486ce585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_input']/div/div/div/textarea</value>
      <webElementGuid>74e3e482-7d54-4569-9fdf-d65554cf9bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/textarea</value>
      <webElementGuid>3e2abef3-58e9-4a31-9ffb-a77235426b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'comments' and @name = 'value[]']</value>
      <webElementGuid>34b894bb-3715-4c12-92b3-6b2067a6ac43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
